### ISSUE TITLE
Validation failed:  recaptcha value is required

### ISSUE THREAD

**Issue by calebebteixeira** [irvinlim/acf-recaptcha#1]
I use the last version of ACF 5 and this error happens everytime. Im using Validate Field plugin too.

**Comment by irvinlim** [comment]
@Cacskate I am only able to replicate this issue when I add the field to the backend. 

Take note that this plugin is **meant to be used only on frontend forms** - it doesn't make sense to add reCAPTCHA to your backend! Nevertheless, I have disabled the field from showing up (as well as validation from occuring) on the backend, to prevent issues with updating the page from the backend.

You should also update the plugin via the [Wordpress plugins repository](https://wordpress.org/plugins/advanced-custom-fields-recaptcha-field/) to keep up with future updates!

I am closing this issue as resolved, unless you really require reCAPTCHA on your backend, which I will try and add that in when I find the time.

Let me know if I have misunderstood. Thank you for your support!
