### ISSUE TITLE
Validation problems

### ISSUE THREAD

**Issue by Karsten-Goetz** [irvinlim/acf-recaptcha#32]
Hi there, I'm using acf-recaptcha and having problems with validation. It seems mainly a Safari Problem  and the value in the function validate_value($valid, $value, $field, $input) { ...} is always empty, therefore the error 'Please click the checkbox.' is shown even if the captcha is checked. I'm using your Plugin together with AdvancedForms Plugin for ACF - don't know if this could be part of the issue. Do you have any idea to solve the problem? Using Mac High Sierra / Safari Version 11.0.2 (13604.4.7.1.3) On Chrome it seams to work...

**Comment by irvinlim** [comment]
Can you check if there's any JavaScript errors in the console? It seems like there's a problem with the AJAX validation to me.

**Comment by trvswgnr** [comment]
I'm getting the same problem. In the console I'm getting the error "Uncaught Error: reCAPTCHA has already been rendered in this element", but there is only one recaptcha field in the form.

**Comment by Karsten-Goetz** [comment]
@irvinlim Sorry, just seen your request: I'll check for JavaScript Errors and report later. I think i was getting same Error like @trvswgnr .

**Comment by irvinlim** [comment]
Since there were no updates for a while, I'll be closing this issue. Feel free to reopen if you still have any questions, thank you.
