### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by jilson23** [irvinlim/acf-recaptcha#33]
sorry my english is bad.

hi, i have a problem, when i active the plugin and send the form this generate error 500, without using it, when i use it, i try using with the flag,

this is the code 

`		<?php while ( have_posts() ) : the_post(); ?>

			<?php acf_form(array(
				'post_id'		=> 'new_post',
				'post_title' => true,
				'new_post'		=> array(
					'post_type'		=> 'jugadores_habiles',
					'post_status'		=> 'pending',
				),
				'fields' => array(
					'apellido-jugador',
                                          'capt-seguridad',
				),
				'updated_message' => __("Se ha guardado tu mensaje, en poco tiempo validaremos tus datos", 'acf'),
				'submit_value'		=> 'Enviar',
                                  'recaptcha' => true
			)); ?>

		<?php endwhile; ?>`

**Comment by irvinlim** [comment]
Hi, can you [turn on error reporting](https://stackoverflow.com/a/21429652/2037090) first to verify what error is being thrown. Without any information I cannot help you, I am sorry.

**Comment by gabestev** [comment]
this probably related to acf_decrypt function. when we are using acf version which not updated. it happens to me. and i remove the decrypt function

**Comment by irvinlim** [comment]
@gabestev In that case, mind providing versions of ACF, WordPress and the ACF reCAPTCHA plugin?

Please also provide some code/screenshots, it would be best if you can provide a live demo site, as I don't actively work on WordPress any more.

**Comment by irvinlim** [comment]
Since there were no updates for a while, I'll be closing this issue. Feel free to reopen if you still have any questions, thank you.
