### ISSUE TITLE
recaptcha expired when submitted

### ISSUE THREAD

**Issue by gabestev** [irvinlim/acf-recaptcha#34]
@irvinlim perhaps you can clue me why recaptcha validation expired? i did it exactly like in the guide. Please help me about it. 

Thank you

**Comment by irvinlim** [comment]
Can you provide a screenshot and some code please? @gabestev

**Comment by irvinlim** [comment]
Since there were no updates for a while, I'll be closing this issue. Feel free to reopen if you still have any questions, thank you.
