### ISSUE TITLE
Add defaults (E_NOTICE)

### ISSUE THREAD

**Issue by Langmans** [irvinlim/acf-recaptcha#36]
To suppress php errors, one can turn off debugging, but when developing themes, you most likely will have this on. Workaround:

```php
add_filter( 'default_option_acf_recaptcha', function ( $default ) {
    return (array) $default + [ 'site_key' => '', 'secret_key' => '' ];
});

**Comment by irvinlim** [comment]
Thanks @rubenvincenten, I think this workaround could be merged in to handle default settings, or handle it directly here: https://github.com/irvinlim/acf-recaptcha/blob/master/acf-recaptcha-v5.php#L14-L15.

I haven't worked on this for a while so I would really appreciate a PR if you wish to help!
