### ISSUE TITLE
Error on submit

### ISSUE THREAD

**Issue by hirasso** [irvinlim/acf-recaptcha#6]
Hi there, I would love to use this, but I'm getting the following error on form sunbmission:

``` javascript
jquery.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'length' in 0
```

My form works just fine until I activate the plugin. Does the site have to be on the domain I have created the recaptcha keys for? I'm developing locally on my machine.

EDIT: I'm using jQuery v1.11.3

**Comment by derby** [comment]
I get the same error on form submission.
**@hirasso:** Did you find a solution?
**@irvinlim:** Could you please check and give support to solve this issue?

**Comment by irvinlim** [comment]
Unfortunately, I cannot replicate the problem. Do check if the update solves your issue.
