### ISSUE TITLE
PHP API documentation

### ISSUE THREAD

**Issue by jmarceli** [irvinlim/acf-recaptcha#8]
ACF has easy PHP API for defining field directly in code (https://www.advancedcustomfields.com/resources/register-fields-via-php/) so it might be useful to provide some docs. I'm ready to make a PR if you like this idea.

**Comment by irvinlim** [comment]
Hi, thanks for the suggestion! Unfortunately I've stopped working on WordPress or ACF for quite a while already, so I'm not really familiar with this any more. I'm welcome if you wish to contribute the docs though!
