### ISSUE TITLE
ReCaptcha false positives

### ISSUE THREAD

**Issue by jmarceli** [irvinlim/acf-recaptcha#9]
Hi, I'm getting a lot of false positives, Even if my ReCaptcha widget shows successful verification the form is unable to pass server side checks. Here is similar issue described: https://groups.google.com/forum/#!topic/recaptcha/dgBo2HXQsN8

I was wondering if it is a good idea to check for validation errors instead of checking `isSuccess()` in `validate_value` method. Quick fix code might look like this:

```
function validate_value( $valid, $value, $field, $input ){
  if (!strlen($value)) return false;

  $api = new \ReCaptcha\ReCaptcha($field['secret_key']);
  $response = $api->verify($value, $_SERVER['REMOTE_ADDR']);
  if ( $response->isSuccess() ) return $valid;

  $errors = $response->getErrorCodes();
  if ( empty( $errors ) ) return $valid;
  return 'Invalid reCaptcha value ' . $value . ' response isSuccess(): ' . ($response->isSuccess() ? 'true' : 'false' ) . ' errors: ' . json_encode($errors);
}
```

I'm using ACF 5.4.2 PRO.

**Comment by minhmanbui** [comment]
thanks you it work for me

**Comment by irvinlim** [comment]
@jmarceli @minhmanbui 

Apologies for the late reply, been caught up with other business.

I'm unable to get any false positives, but the code looks fine to me. I've merged in your suggestions, hopefully this works for others as well.

Unfortunately I've stopped working on WordPress for about a year already, so I'm unable to test this really in depth. Hopefully this solves your issues!
